"""Verify the runtime bundle contains exactly the lab/drills package code the worker needs."""

from __future__ import annotations

import zipfile
from pathlib import Path

from tools.export_runtime_bundle import write_runtime_bundle

ROOT = Path(__file__).resolve().parents[1]


def _build_sample_packages(tmp_path: Path) -> tuple[Path, Path]:
    """Create a small lab/drills tree covering every exclusion this bundle must honor."""
    lab_path = tmp_path / "lab"
    drills_path = tmp_path / "drills"

    (lab_path / "__pycache__").mkdir(parents=True)
    (lab_path / "__pycache__" / "loop.cpython-311.pyc").write_bytes(b"cached")
    (lab_path / "loop.py").write_text("def run() -> None: ...\n", encoding="utf-8")
    (lab_path / "evals").mkdir()
    (lab_path / "evals" / "golden.py").write_text("GOLDEN = 1\n", encoding="utf-8")
    (lab_path / "evals" / "golden_cases.yaml").write_text("cases: []\n", encoding="utf-8")
    (lab_path / "README.md").write_text("# lab\n", encoding="utf-8")

    (drills_path / "engine").mkdir(parents=True)
    (drills_path / "engine" / "validation.py").write_text("SCHEMA = 1\n", encoding="utf-8")
    (drills_path / "schema.json").write_text("{}\n", encoding="utf-8")
    (drills_path / "bank" / "01-domain").mkdir(parents=True)
    (drills_path / "bank" / "01-domain" / "item.yaml").write_text("id: 1\n", encoding="utf-8")
    (drills_path / "mocks").mkdir()
    (drills_path / "mocks" / "recorded.py").write_text("RECORDED = 1\n", encoding="utf-8")
    (drills_path / ".pytest_cache").mkdir()
    (drills_path / ".pytest_cache" / "state.json").write_text("{}\n", encoding="utf-8")

    return lab_path, drills_path


def _archive_names(archive_path: Path) -> set[str]:
    with zipfile.ZipFile(archive_path) as archive:
        return set(archive.namelist())


def test_bundle_contains_importable_lab_and_drills_modules(tmp_path: Path) -> None:
    """The archive holds the .py sources and the package data those sources actually read."""
    lab_path, drills_path = _build_sample_packages(tmp_path)
    output_path = tmp_path / "lab-drills.zip"

    write_runtime_bundle(lab_path, drills_path, output_path)

    names = _archive_names(output_path)
    assert "lab/loop.py" in names
    assert "lab/evals/golden.py" in names
    assert "lab/evals/golden_cases.yaml" in names
    assert "drills/engine/validation.py" in names
    assert "drills/schema.json" in names


def test_bundle_excludes_study_content_and_build_artifacts(tmp_path: Path) -> None:
    """The archive never contains caches, mocks, or the study-content bank directory."""
    lab_path, drills_path = _build_sample_packages(tmp_path)
    output_path = tmp_path / "lab-drills.zip"

    write_runtime_bundle(lab_path, drills_path, output_path)

    names = _archive_names(output_path)
    assert not any("__pycache__" in name for name in names)
    assert not any(name.endswith(".pyc") for name in names)
    assert not any(".pytest_cache" in name for name in names)
    assert not any(name.startswith("drills/mocks/") for name in names)
    assert not any(name.startswith("drills/bank/") for name in names)
    assert "lab/README.md" not in names


def test_bundle_excludes_every_study_content_root_by_construction(tmp_path: Path) -> None:
    """Notes, cheatsheets, guides, and study plans never enter the bundle: it never walks them.

    Built here from the repository's real ``lab/`` and ``drills/`` rather than read from
    ``site/public/runtime/``. That artifact is generated by the site's prebuild, so a clean
    checkout does not have one and this test would fail for a reason that says nothing about the
    property it is checking.
    """
    output = tmp_path / "lab-drills.zip"
    write_runtime_bundle(ROOT / "lab", ROOT / "drills", output)
    names = _archive_names(output)

    assert names, "The bundle built from the repository's own packages is empty."
    for study_root in ("notes/", "cheatsheets/", "guide/", "study-plans/"):
        assert not any(name.startswith(study_root) for name in names)


def test_bundle_generation_is_byte_identical_across_runs(tmp_path: Path) -> None:
    """Identical lab/drills inputs must produce identical archive bytes; a rebuild never churns."""
    lab_path, drills_path = _build_sample_packages(tmp_path)
    first_output = tmp_path / "first.zip"
    second_output = tmp_path / "second.zip"

    write_runtime_bundle(lab_path, drills_path, first_output)
    write_runtime_bundle(lab_path, drills_path, second_output)

    assert first_output.read_bytes() == second_output.read_bytes()
